version: "3.7"
services:
  proxy:
    build:
      context: envoy
      dockerfile: Dockerfile
    networks:
      - envoymesh
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
    ports:
      - "8000:8000"

  web_service:
    build:
      context: web-service
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8080:80"

networks:
  envoymesh: {}
